version: '3.9'

services:
  muconeup:
    image: ghcr.io/berntpopp/muconeup/muconeup:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./data:/data
      - ./output:/output
      - ./config.json:/app/config.json:ro
    environment:
      - MUCONEUP_LOG_LEVEL=${LOG_LEVEL:-INFO}
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
